/* Enable PCC PORTS */

#define PCC_PORTB PCC_PORTB_INDEX
#define PCC_PORTC PCC_PORTC_INDEX
#define PCC_PORTD PCC_PORTD_INDEX
#define PCC_PORTE PCC_PORTE_INDEX

#define enableClocksPort(PORT) PCC->PCCn[PORT]=PCC_PCCn_CGC_MASK
